import React from "react";
import figma from "@figma/code-connect";

import { PrimaryButton } from "./PrimaryButton";

/**
 * -- This file was auto-generated by Code Connect (and adjusted) --
 * Keep this mapping in sync with `PrimaryButton` props.
 */
figma.connect(
  PrimaryButton,
  "https://www.figma.com/design/g4qBmpJru6aI4fGQZbndch/Untitled?node-id=9%3A15",
  {
    props: {
      children: figma.string("Text"),
    },
    example: (props) => (
      <PrimaryButton icon={null}>{props.children}</PrimaryButton>
    ),
  },
);
