import React from "react"
import { PrimaryButton } from "./PrimaryButton"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  PrimaryButton,
  "https://www.figma.com/design/g4qBmpJru6aI4fGQZbndch/Untitled?node-id=2%3A73",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      text: figma.string("Text"),
      // No matching props could be found for these Figma properties:
      // "text": figma.string('Text')
    },
    example: (props) => <PrimaryButton text={props.text} />,
  },
)
